#!/bin/bash
## colors
red="\e[1;31m"
green="\e[1;32m"
brown="\e[1;33m" # (Yellow)
blue="\e[1;34m"  # (Orange)
violet="\e[1;35m"
cyan="\e[1;36m"
colnull="\e[0m"

## wallart

echo " ▐ ▄  ▄▄▄·  ▌ ▐·"
echo "•█▌▐█▐█ ▀█ ▪█·█▌"
echo "▐█▐▐▌▄█▀▀█ ▐█▐█•"
echo "██▐█▌▐█ ▪▐▌ ███ "
echo "▀▀ █▪ ▀  ▀ . ▀  "


## code

if [ -z "$1" ]
then
    echo -e "$red[!]$colnull Empty Arguments"
    exit 0
fi

echo -e "$blue[?]$colnull Connecting ADB"
echo -e $(adb connect $1 | sed 's/^/\\e[1;33m[i]\\e[0m /' 2>&1)
echo -e "\n$blue[?]$colnull Forcing Navbar"
adb shell settings put global force_fsg_nav_bar 1
echo -e "$green[!] DONE$colnull"
echo -e "\n$blue[?]$colnull Disconnecting ADB"
echo -e $(adb disconnect | sed 's/^/\\e[1;33m[i]\\e[0m /')
echo -e "$green[!] EVERYTHING DONE$colnull"
